image:
  file: .gitpod.Dockerfile

ports:
    - port: 3000
      onOpen: ignore

vscode:
  extensions:
    - learn-pack.learnpack-vscode
    
github:
    prebuilds:
        # enable for the master/default branch (defaults to true)
        master: true
        # enable for pull requests coming from this repo (defaults to true)
        pullRequests: false
        # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
        addComment: false

additionalRepositories:
    - url: https://github.com/enachb/AutoGPT-trading.git
      # checkoutLocation is relative to /workspaces
      checkoutLocation: autogpt-trading

workspaceLocation: trade-chat/main.code-workspace # Relative to /workspace dir
